// <auto-generated />
using System;
using AdminHerramientas.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdminHerramientas.Server.Migrations
{
    [DbContext(typeof(AlpContext))]
    partial class AlpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdminHerramientas.Shared.Models.Concesionario", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<int>("FkIdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("fk_IdEmpresa");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasMaxLength(55)
                        .IsUnicode(false)
                        .HasColumnType("varchar(55)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(155)
                        .IsUnicode(false)
                        .HasColumnType("varchar(155)");

                    b.Property<int>("UsuarioModifico")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__concesio__3214EC07B3684BDA");

                    b.HasIndex("FkIdEmpresa");

                    b.ToTable("Concesionarios");
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("EsAgencia")
                        .HasColumnType("bit");

                    b.Property<string>("RFC")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("RFC");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(155)
                        .IsUnicode(false)
                        .HasColumnType("varchar(155)");

                    b.Property<DateTime>("fechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fechaModificacion");

                    b.Property<int>("usuarioModifico")
                        .HasColumnType("int")
                        .HasColumnName("usuarioModifico");

                    b.HasKey("Id")
                        .HasName("PK__Empresas__3214EC07727B5B99");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.Herramienta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UsuarioModifico")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Herramie__3214EC0786FC08B3");

                    b.ToTable("Herramientas");
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.HerramientasDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("Disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Estado")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Etiqueta")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("FechaCompra")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<int?>("FkIdHerramienta")
                        .HasColumnType("int")
                        .HasColumnName("Fk_IdHerramienta");

                    b.Property<int>("UsuarioModifico")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Herrrami__3214EC07BA3C80B3");

                    b.HasIndex("FkIdHerramienta");

                    b.ToTable("HerramientasDetalle", (string)null);
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.HistorialMantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("FkBastidor")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("fk_bastidor");

                    b.Property<int>("IdConcesionario")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioModifico")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaMantenimiento")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("FkBastidor");

                    b.HasIndex("IdConcesionario");

                    b.ToTable("historial_mantenimientos");
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.Intervalo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("activo")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_modificacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Intervalo_dias")
                        .HasColumnType("int")
                        .HasColumnName("intervalo_dias");

                    b.Property<int?>("UsuarioModifico")
                        .HasColumnType("int")
                        .HasColumnName("usuario_modifico");

                    b.Property<string>("marcavehiculo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("marcavehiculo");

                    b.HasKey("Id");

                    b.ToTable("Intervalos", (string)null);
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.Nip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaModificacion");

                    b.Property<string>("Fk_codigoOperario")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("fk_codigoOperario");

                    b.Property<int>("UsuarioModifico")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioModifico");

                    b.Property<string>("ValorNip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("nip");

                    b.HasKey("Id");

                    b.HasIndex("Fk_codigoOperario")
                        .IsUnique();

                    b.ToTable("Nips", (string)null);
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.Operario", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<int>("IdTaller")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Seccion")
                        .HasMaxLength(55)
                        .IsUnicode(false)
                        .HasColumnType("varchar(55)");

                    b.Property<int>("UsuarioModifico")
                        .HasColumnType("int")
                        .HasColumnName("usuarioModifico");

                    b.HasKey("Codigo")
                        .HasName("PK__Operario__06370DAD992741FD");

                    b.ToTable("Operarios");
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.Prestamo", b =>
                {
                    b.Property<int>("IdPrestamos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrestamos"));

                    b.Property<bool?>("Activo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("CodigoServicio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigoServicio");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime")
                        .HasColumnName("fechaSolicitud");

                    b.Property<string>("FkCodigoEncargado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("fk_codigoEncargado");

                    b.Property<string>("FkCodigoOperario")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("fk_codigoOperario");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("motivo");

                    b.Property<int>("UsuarioModifico")
                        .HasColumnType("int");

                    b.HasKey("IdPrestamos")
                        .HasName("PK__Prestamo__C9249103DF55833E");

                    b.HasIndex("FkCodigoEncargado");

                    b.HasIndex("FkCodigoOperario");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.PrestamosDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("activo")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Comentario")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("comentario");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("date")
                        .HasColumnName("fechaEntrega");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<int>("FkIdHerramienta")
                        .HasColumnType("int")
                        .HasColumnName("fk_IdHerramienta");

                    b.Property<int>("FkIdPrestamo")
                        .HasColumnType("int")
                        .HasColumnName("fk_IdPrestamo");

                    b.Property<int>("UsuarioModifico")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Prestamo__3214EC07C59C3ECB");

                    b.HasIndex("FkIdPrestamo");

                    b.ToTable("Prestamos_Detalle", (string)null);
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.RegistrosLavado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("Activo")
                        .HasDefaultValueSql("((1))");

                    b.Property<decimal>("ComisionRegistro")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("comisionRegistro");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaModificacion");

                    b.Property<string>("FkBastidor")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("fk_bastidor");

                    b.Property<string>("FkCodigoOperario")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("fk_codigoOperario");

                    b.Property<int>("FkIdTarea")
                        .HasColumnType("int")
                        .HasColumnName("fk_IdTarea");

                    b.Property<int>("UsuarioModifico")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioModifico");

                    b.HasKey("Id");

                    b.HasIndex("FkBastidor");

                    b.HasIndex("FkCodigoOperario");

                    b.HasIndex("FkIdTarea");

                    b.ToTable("Registros_lavados", (string)null);
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("Activo")
                        .HasDefaultValueSql("((1))");

                    b.Property<decimal>("ComisionTarea")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("comisionTarea");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaModificacion");

                    b.Property<string>("NombreTarea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombreTarea");

                    b.Property<int>("UsuarioModifico")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioModifico");

                    b.HasKey("Id");

                    b.ToTable("Tareas", (string)null);
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.Vehiculo", b =>
                {
                    b.Property<string>("Idv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("IDV");

                    b.Property<string>("AnioVehi")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ANIO_VEHI");

                    b.Property<string>("Bastidor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("BASTIDOR");

                    b.Property<string>("Color")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("COLOR");

                    b.Property<string>("DesColor")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DES_COLOR");

                    b.Property<string>("DesFamilia")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DES_FAMILIA");

                    b.Property<string>("DesMarca")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DES_MARCA");

                    b.Property<string>("DesModelo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DES_MODELO");

                    b.Property<string>("Familia")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FAMILIA");

                    b.Property<DateTime>("Fechafin")
                        .HasColumnType("date")
                        .HasColumnName("FECHAFIN");

                    b.Property<decimal?>("Km")
                        .HasColumnType("numeric(10, 0)")
                        .HasColumnName("KM");

                    b.Property<string>("Marca")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("MARCA");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("MODELO");

                    b.HasKey("Idv")
                        .HasName("PK__Vehiculo__C4971C38CDABDCC6");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.Concesionario", b =>
                {
                    b.HasOne("AdminHerramientas.Shared.Models.Empresa", "Empresa")
                        .WithMany("Concesionarios")
                        .HasForeignKey("FkIdEmpresa")
                        .IsRequired()
                        .HasConstraintName("FK_Concesionarios_Empresas");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.HerramientasDetalle", b =>
                {
                    b.HasOne("AdminHerramientas.Shared.Models.Herramienta", "FkIdHerramientaNavigation")
                        .WithMany("HerramientasDetalles")
                        .HasForeignKey("FkIdHerramienta")
                        .HasConstraintName("FK_HerramientasDetalles_Herramientas");

                    b.Navigation("FkIdHerramientaNavigation");
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.HistorialMantenimiento", b =>
                {
                    b.HasOne("AdminHerramientas.Shared.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("FkBastidor")
                        .HasPrincipalKey("Bastidor")
                        .HasConstraintName("FK_Historial_Vehiculo_Bastidor");

                    b.HasOne("AdminHerramientas.Shared.Models.Concesionario", "Concesionario")
                        .WithMany()
                        .HasForeignKey("IdConcesionario")
                        .IsRequired()
                        .HasConstraintName("FK_Historial_Concesionarios");

                    b.Navigation("Concesionario");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.Nip", b =>
                {
                    b.HasOne("AdminHerramientas.Shared.Models.Operario", null)
                        .WithOne("Nip")
                        .HasForeignKey("AdminHerramientas.Shared.Models.Nip", "Fk_codigoOperario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.Prestamo", b =>
                {
                    b.HasOne("AdminHerramientas.Shared.Models.Operario", "FkCodigoEncargadoNavigation")
                        .WithMany("PrestamoFkCodigoEncargadoNavigations")
                        .HasForeignKey("FkCodigoEncargado")
                        .IsRequired()
                        .HasConstraintName("FK_Prestamos_Encargado");

                    b.HasOne("AdminHerramientas.Shared.Models.Operario", "FkCodigoOperarioNavigation")
                        .WithMany("PrestamoFkCodigoOperarioNavigations")
                        .HasForeignKey("FkCodigoOperario")
                        .IsRequired()
                        .HasConstraintName("FK_Prestamos_Operarios");

                    b.Navigation("FkCodigoEncargadoNavigation");

                    b.Navigation("FkCodigoOperarioNavigation");
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.PrestamosDetalle", b =>
                {
                    b.HasOne("AdminHerramientas.Shared.Models.Prestamo", "FkIdPrestamoNavigation")
                        .WithMany("PrestamosDetalles")
                        .HasForeignKey("FkIdPrestamo")
                        .IsRequired()
                        .HasConstraintName("FK_PrestamosDetalle_Prestamos");

                    b.Navigation("FkIdPrestamoNavigation");
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.RegistrosLavado", b =>
                {
                    b.HasOne("AdminHerramientas.Shared.Models.Vehiculo", "VehiculoNavigation")
                        .WithMany()
                        .HasForeignKey("FkBastidor")
                        .HasPrincipalKey("Bastidor")
                        .HasConstraintName("FK_Lavados_Vehiculo_Bastidor");

                    b.HasOne("AdminHerramientas.Shared.Models.Operario", "OperarioNavigation")
                        .WithMany("RegistrosLavados")
                        .HasForeignKey("FkCodigoOperario")
                        .IsRequired()
                        .HasConstraintName("FK_Lavados_Operarios");

                    b.HasOne("AdminHerramientas.Shared.Models.Tarea", "TareaNavigation")
                        .WithMany("RegistrosLavados")
                        .HasForeignKey("FkIdTarea")
                        .IsRequired()
                        .HasConstraintName("FK_Lavados_Tareas");

                    b.Navigation("OperarioNavigation");

                    b.Navigation("TareaNavigation");

                    b.Navigation("VehiculoNavigation");
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.Empresa", b =>
                {
                    b.Navigation("Concesionarios");
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.Herramienta", b =>
                {
                    b.Navigation("HerramientasDetalles");
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.Operario", b =>
                {
                    b.Navigation("Nip");

                    b.Navigation("PrestamoFkCodigoEncargadoNavigations");

                    b.Navigation("PrestamoFkCodigoOperarioNavigations");

                    b.Navigation("RegistrosLavados");
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.Prestamo", b =>
                {
                    b.Navigation("PrestamosDetalles");
                });

            modelBuilder.Entity("AdminHerramientas.Shared.Models.Tarea", b =>
                {
                    b.Navigation("RegistrosLavados");
                });
#pragma warning restore 612, 618
        }
    }
}
